name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose-run
        shell: bash
        run: |
          docker-compose up -d
          docker-compose exec -T web rails t
